# @name getAllTasks
GET  http://localhost:3000/tasks

###

# @name postTask
POST http://localhost:3000/tasks
content-type: application/json

{
    "name": "Eat"
}

###

# @name getTask
GET  http://localhost:3000/tasks/{{postTask.response.body.$._id}}

###

# @name updateTask
PUT  http://localhost:3000/tasks/{{postTask.response.body.$._id}}
content-type: application/json

{
    "status": "ongoing"
}

###

# @name deleteTask
DELETE http://localhost:3000/tasks/{{postTask.response.body.$._id}}
